name: interact_cli
description: A collection of customizable interactive command-line components.
version: 2.4.0
repository: https://github.com/payam-zahedi/interact

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  dart_console:
  meta: ^1.16.0
  tint: ^2.0.1

dev_dependencies:
  lint: ^2.8.0
  test: ^1.25.15
